name = "lemholder"
account_id = "5bcbe073561611052ae8358559c2709c"
workers_dev = true
compatibility_date = "2022-01-31"
main = "./dist/index.mjs"
node_compat = true

[build]
command = "npm install && npm run build"

# [[build.upload.rules]]
# type = "Data"
# globs = ["**/*.ttf", "**/*.otf"]
# fallthrough = true

[[rules]]
type = "Data"
globs = [ "**/*.ttf", "**/*.otf" ]
fallthrough = true